inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  marching_cubes_bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  keyframe_every: 5
start_index: 0
#end_index: 2034
end_index: 500
enable_loop_detect: False
grid:
  oneGrid: False
  

data:
  datadir: /data0/dataset/scannet/scans/scene0000_00
  trainskip: 1
  output: output/scannet/scene0000_00
  exp_name: demo0909