inherit_from: configs/Azure/azure.yaml
mapping:
  bound: [[-1.5,3.5],[-4.5,3.6],[-6.5,8.]]
  marching_cubes_bound: [[-1.5,3.5],[-4.5,3.6],[-6.5,8.]]

data:
  datadir: /data0/dataset/Apartment
  trainskip: 1
  output: output/Apartment
  exp_name: demo_0530_nsloss

planes_res:
  coarse: 0.02
  fine: 0.01
  bound_dividable: 0.02

c_planes_res:
  coarse: 0.08
  fine: 0.02


model:
  c_dim: 32
  truncation: 0.1
  #input_ch: 128 #64
  input_ch: 64
  input_ch_pos: 48

scale: 1

#grid:
#  oneGrid: False