inherit_from: /data0/wjy/sgl/Co-SLAM-main-1/configs/Indoor/indoor.yaml
mapping:
#  bound: [[-1.7,60.],[-12.,0.4],[-1.,2.1]]
#  marching_cubes_bound: [[-1.7,60.],[-12.,0.4],[-1.,2.1]]

#  bound: [[-1,12.],[-1.,2.1],[-60.,1.7]]
#  marching_cubes_bound: [[-1,12.],[-1.,2.1],[-60.,1.7]]

#for ori trans part
  bound: [ [ -3.,15. ],[ -5.,4. ],[ -5.,61. ] ]
  marching_cubes_bound: [[-3.,15.],[-5.,4.],[-5.,61.]]
start_index: 0
end_index: 4613

#  bound: [ [ -2.,4. ],[ -5.,4. ],[ -5.,53. ] ]
#  marching_cubes_bound: [ [ -2.,4. ],[ -5.,4. ],[ -5.,53. ] ]
#start_index: 0
#end_index: 1700
#loop_kf1_id: 1300
#loop_kf2_id: 1300
#enable_loop_detect: True

#  bound: [ [ -0.5,13. ],[ -5. ,4. ],[ 30.,61. ] ]
#  marching_cubes_bound: [ [ -0.5,13. ],[ -5. ,4. ],[ 30.,61. ] ]
#start_index: 1300
#end_index: 3000
#loop_kf1_id: 2631
#loop_kf2_id: 2630
#enable_loop_detect: True

#  bound: [ [ 8.,15. ],[ -5.,4. ],[ -5.,61. ] ]
#  marching_cubes_bound: [[8.,15.],[-5.,4.],[-5.,61.]]
#start_index: 2600
#end_index: 3900
#loop_kf1_id: 3323
#loop_kf2_id: 3323
#enable_loop_detect: True

#  bound: [ [ -3.,15. ],[ -5.,4. ],[ -5.,40. ] ]
#  marching_cubes_bound: [[-3.,15.],[-5.,4.],[-5.,40.]]
#start_index: 3300
#end_index: 4613
#enable_loop_detect: False

#xyz 1.67 -0.40 -0.03
#左右 下上 前后
#左右 9.56 左0.4右9.16\ 上下2.55 下0.45上2.1\ 前1.71后 60
#相机高0.45

data:
  datadir: /data0/wjy/sgl/DATASET/Indoor/indoor_sq1
  trainskip: 1
  output: output/Indoor/indoor_sq1
  exp_name: 0910_trans_part1_nosmooth

planes_res:
  coarse: 0.04
  fine: 0.02
  bound_dividable: 0.02

mesh:
  voxel_final: 0.02


#c_planes_res:
#  coarse: 0.08
#  fine: 0.02

#planes_res:
#  coarse: 0.08
#  fine: 0.02
#  bound_dividable: 0.02

c_planes_res:
  coarse: 0.02
  fine: 0.01

model:
  c_dim: 32
  truncation: 0.1
  #input_ch: 128 #64
  input_ch: 64
  input_ch_pos: 48

scale: 1

grid:
  oneGrid: False