inherit_from: configs/Indoor/indoor.yaml
mapping:
  bound: [[-6.2,50.],[-6.5,-2.2],[-2.0, 4.5]]
  marching_cubes_bound: [[-6.2,50.],[-6.5,-2.2],[-2.0, 4.5]]
  first_mesh: True
  first_iters: 500
start_index: 0
end_index: 1700

#cam:
#  H: 720
#  W: 1280
#  fx: 637.147
#  fy: 636.668
#  cx: 637.003
#  cy: 363.032

data:
  trainskip: 1
  output: output/Indoor/Indoor
  exp_name: 1129_rs
is_co_sdf: False
enable_loop_detect: True
model:
  c_dim: 32
  truncation: 0.1
  #input_ch: 128 #64
  input_ch: 64
  input_ch_pos: 48

scale: 1

grid:
  oneGrid: False
mesh:
  voxel_final: 0.03

planes_res:
  coarse: 0.24
  fine: 0.06
  bound_dividable: 0.24
c_planes_res:
  coarse: 0.24
  fine: 0.06

rank: 3