inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.2,3.9],[-9.5,-1.9],[1.1,3.8]]
  marching_cubes_bound: [[-3.2,3.9],[-9.5,-1.9],[1.1,3.8]]
data: 
  datadir: DATASET/Apart-0/apart_0_part1
  trainskip: 1
  output: output/Apart-0/apart_0
  exp_name: part1
enable_loop_detect: False
start_index: 0
end_index: 2500
is_co_sdf: False
