inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-2.8,8.2],[-1.1,8.5],[-2,1.3]]
  marching_cubes_bound: [[-2.8,8.2],[-1.1,8.5],[-2,1.3]]
data: #/data0/dataset/Replica/room0
  datadir: /data0/wjy/sgl/DATASET/Apart-2/apart_2_part2
  trainskip: 1
  output: output/Apart-2/apart_2_part2
  exp_name: 0920_2
enable_loop_detect: False

mesh:
  voxel_final: 0.01

grid:
  oneGrid: False