inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.2,3.9],[-9.5,-1.9],[1.1,3.8]]
  marching_cubes_bound: [[-3.2,3.9],[-9.5,-1.9],[1.1,3.8]]
data: #/data0/dataset/Replica/room0
  datadir: /data0/wjy/sgl/DATASET/Apart-0/apart_0_part2
  trainskip: 1
  output: output/Apart-0/apart_0_part2
  exp_name: 0921
enable_loop_detect: False

grid:
  oneGrid: False