inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.4,5.5],[-2.5,4.4],[-1.4,1.8]]
  marching_cubes_bound: [[-1.3,5.4],[-2.4,4.3],[-1.3,1.7]]


data:
  datadir: /data0/wjy/ESLAM/Datasets/Replica/office4
  trainskip: 1
  output: output/Replica/office4
  exp_name: 1012_e

enable_loop_detect: False
start_index: 0
end_index: 2000

grid:
  oneGrid: True

training:
  n_samples: 256

is_co_sdf: False

meshing:
  level_set: 0
  resolution: 0.02 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
  mesh_bound_scale: 1.02