inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.6,3.2],[-3.0,5.5],[-1.4,1.7]]
  marching_cubes_bound: [[-3.5,3.1],[-2.9,5.4],[-1.3,1.6]]

data:
  datadir: /data0/dataset/Replica/office2
  output: output/Replica/office2
  trainskip: 1
  exp_name: 1129_rs

start_index: 900
end_index: 2000
enable_loop_detect: True
is_co_sdf: False
