inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.6,3.2],[-3.0,5.5],[-1.4,1.7]]
  marching_cubes_bound: [[-3.5,3.1],[-2.9,5.4],[-1.3,1.6]]
  

data:
  datadir:  /data0/dataset/Replica/office2
  trainskip: 1
  output: output/Replica/office2
  exp_name: all

enable_loop_detect: False
start_index: 0
end_index: 2000
is_co_sdf: False
