inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.4,5.5],[-2.5,4.4],[-1.4,1.8]]
  marching_cubes_bound: [[-1.3,5.4],[-2.4,4.3],[-1.3,1.7]]
  
data:
  datadir: /data0/dataset/Replica/office4
  output: output/Replica/office4
  trainskip: 1
  exp_name: 1129_rs

start_index: 0
end_index: 1100

enable_loop_detect: True
is_co_sdf: False
