inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.0,6.1],[-3.4,1.9],[-3.1,0.8]]
  marching_cubes_bound: [[-0.9,6.0],[-3.3,1.8],[-3.0,0.7]]
data:
  datadir:  /data0/dataset/Replica/room2
  trainskip: 1
  output: output/Replica/room2
  exp_name: 1129_rs

start_index: 900
end_index: 2000
enable_loop_detect: True
is_co_sdf: False
